Autoparkl level 1. Classes.
PWMaestro/Autopark pull request #1
Opened 2021-05-18 05:59 UTC by PWMaestro

Created VechileType class.
Completed tasks accordint to level 1.

2021-05-18 06:11 UTC, UNDogMan requested changes
Hi.
I did some comments. Let me know if any questions.

2021-05-18 06:11 UTC, UNDogMan commented on Autopark/Program.cs
> +    class VechileType
Add access method

2021-05-18 06:11 UTC, UNDogMan commented on Autopark/Program.cs
> +        }
U can use auto properties.

2021-05-18 06:11 UTC, UNDogMan commented on Autopark/Program.cs
> +}
Move  class in separate file

2021-05-18 07:33 UTC, UNDogMan requested changes
Check it.

2021-05-18 07:33 UTC, UNDogMan commented on Autopark/VechileType.cs
> +    class VechileType
Public?

2021-05-18 07:33 UTC, UNDogMan commented on Autopark/Program.cs
> +    public class Program
Program class never can be public. Delete that.

2021-05-18 08:01 UTC, UNDogMan approved these changes
Approve

2021-05-19 10:22 UTC, dzmitri-litvinov approved these changes

2021-05-19 10:26 UTC, merged