Level 2 interfaces
PWMaestro/Autopark pull request #2
Opened 2021-05-24 17:27 UTC by PWMaestro

Created Vechile & Printer class.
Completed tasks accordint to level 2.

2021-05-24 20:15 UTC, PushMeNow requested changes
Hi!
I have added some comments. Let me know if any questions.

2021-05-24 20:15 UTC, PushMeNow commented on Autopark/Program.cs
>              }
Move whole logic with searching and printing of max/min mileage in separate method

2021-05-24 20:15 UTC, PushMeNow commented on Autopark/Program.cs
> +            };
Move it in static readonly field.

2021-05-24 20:15 UTC, PushMeNow commented on Autopark/Program.cs
>              };
Move it in static readonly field

2021-05-24 20:15 UTC, PushMeNow commented on Autopark/Vehicle.cs
> +    }
Move it in separate file

2021-05-24 20:15 UTC, PushMeNow commented on Autopark/Vehicle.cs
> +        public readonly string modelName;
User mustn't know about these fields. Also could you add to these fields '_' prefix?

2021-05-24 20:15 UTC, PushMeNow commented on Autopark/Vehicle.cs
> +            this.Color = color;
I don't see the reason in 'this' keyword here.

2021-05-25 08:31 UTC, dzmitri-litvinov approved these changes

2021-05-25 17:04 UTC, PushMeNow approved these changes

2021-05-25 17:14 UTC, merged