Autopark. Level 4. Abstraction
PWMaestro/Autopark pull request #4
Opened 2021-05-26 10:07 UTC by PWMaestro

Change Engine & CombustionEngine classes on abstract;
Override their ToString() methods;
Create Vehicle method GetVehicleWithMaxMileageOnOneFilling();
Complete level 4 according to the task.

2021-05-28 12:32 UTC, dzmitri-litvinov reviewed
Hi:) I have only one comment

2021-05-28 12:32 UTC, dzmitri-litvinov commented on Autopark/Vehicle.cs
> +            return Weight * 0.0013 + Type.TaxCoefficient * EngineType.TaxCoeffByEngineType * 30 + 5;
Constant coefficients could be implemented as const private variables in the class

2021-05-28 14:05 UTC, UNDogMan requested changes
Fix Dmitry comment and it will be ok.

2021-05-28 14:39 UTC, UNDogMan approved these changes
Approve

2021-05-29 12:20 UTC, PushMeNow approved these changes

2021-05-29 12:22 UTC, merged