Add level 5. Custom collections
PWMaestro/Autopark pull request #5
Opened 2021-06-01 07:14 UTC by PWMaestro

Complete the level according to the task.

2021-06-01 08:38 UTC, dzmitri-litvinov approved these changes

2021-06-01 18:02 UTC, UNDogMan requested changes
Check my comments.

2021-06-02 15:58 UTC, PushMeNow requested changes
Hi!
I did some comments. Let me know if any questions

2021-06-02 15:58 UTC, PushMeNow commented on Autopark/AbstractCombustionEngine.cs
> +        public override string ToString() => $"{base.ToString()} {EngineVolume} {FuelConsumptionPer100Km}".Replace(",", ".");
Replace method here is redundant. You can resolve it by CultureInfo of thread. There is a setting for decimal separator.

2021-06-02 15:58 UTC, PushMeNow commented on Autopark/Collections.cs
> +        private static readonly string errorMessage = "Error! Can not find the file: ";
These must be constants. 
What is the filePrefix? Why do you need it?

2021-06-02 15:58 UTC, PushMeNow commented on Autopark/Collections.cs
> +            vehiclesFilePath = filePrefix + vehiclesFileName + fileExtension;
Your files have to be in base directory because in any way we cannot to run in on our PC.

2021-06-02 15:58 UTC, PushMeNow commented on Autopark/Collections.cs
> +                GetVehicleTypeById(LoadTypes(vehicleTypesFilePath), int.Parse(data[1])),
Why you don't use here your prop for types?

2021-06-02 15:58 UTC, PushMeNow commented on Autopark/Collections.cs
> +                        double.Parse(engineStringPieces[1], CultureInfo.InvariantCulture),
Too many CultureInfo.InvariantCulture... Use CultureInfo thread settings

2021-06-02 15:58 UTC, PushMeNow commented on Autopark/Collections.cs
> +        private static VehicleType GetVehicleTypeById(List<VehicleType> typesList, int id)
You can get these types from your prop. You don't need static here and parameter typesList.

2021-06-03 16:49 UTC, PushMeNow approved these changes

2021-06-03 16:57 UTC, merged